//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/cluster_catalog_item_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import type { ClusterTemplateReference } from "./cluster_template_type_pb";
import { file_osac_private_v1_cluster_template_type } from "./cluster_template_type_pb";
import type { FieldDefinition } from "./field_definition_type_pb";
import { file_osac_private_v1_field_definition_type } from "./field_definition_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/cluster_catalog_item_type.proto.
 */
export const file_osac_private_v1_cluster_catalog_item_type: GenFile = /*@__PURE__*/
  fileDesc("Ci9vc2FjL3ByaXZhdGUvdjEvY2x1c3Rlcl9jYXRhbG9nX2l0ZW1fdHlwZS5wcm90bxIPb3NhYy5wcml2YXRlLnYxIpYCChJDbHVzdGVyQ2F0YWxvZ0l0ZW0SCgoCaWQYASABKAkSKwoIbWV0YWRhdGEYAiABKAsyGS5vc2FjLnByaXZhdGUudjEuTWV0YWRhdGESDQoFdGl0bGUYAyABKAkSEwoLZGVzY3JpcHRpb24YBCABKAkSOwoIdGVtcGxhdGUYBSABKAsyKS5vc2FjLnByaXZhdGUudjEuQ2x1c3RlclRlbXBsYXRlUmVmZXJlbmNlEhEKCXB1Ymxpc2hlZBgGIAEoCBIWCgZ0ZW5hbnQYByABKAlCBoq1GAIIARI7ChFmaWVsZF9kZWZpbml0aW9ucxgIIAMoCzIgLm9zYWMucHJpdmF0ZS52MS5GaWVsZERlZmluaXRpb24iWAobQ2x1c3RlckNhdGFsb2dJdGVtUmVmZXJlbmNlEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSDwoHcHJvamVjdBgDIAEoCRIOCgZzaGFyZWQYBCABKAhCFIq1GBASDm9zYWMucHVibGljLnYxYgZwcm90bzM", [file_cleanapi_cleanapi, file_osac_private_v1_cluster_template_type, file_osac_private_v1_field_definition_type, file_osac_private_v1_metadata_type]);

/**
 * A cluster catalog item defines a curated infrastructure offering that references an underlying cluster template.
 * Admins control which fields users can set, enforce defaults, and validate input via JSON Schema.
 *
 * buf:lint:ignore OSAC_OBJECT_SHAPE
 *
 * @generated from message osac.private.v1.ClusterCatalogItem
 */
export type ClusterCatalogItem = Message<"osac.private.v1.ClusterCatalogItem"> & {
  /**
   * Unique identifier of the catalog item.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the catalog item, suitable for displaying in one single line on a UI or CLI.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the catalog item, using Markdown format.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Reference to the underlying cluster template that this catalog item references.
   *
   * @generated from field: osac.private.v1.ClusterTemplateReference template = 5;
   */
  template?: ClusterTemplateReference | undefined;

  /**
   * Whether this catalog item is published.
   *
   * @generated from field: bool published = 6;
   */
  published: boolean;

  /**
   * Tenant scope for this catalog item. An empty string means the item is global and visible to all tenants. A
   * non-empty string scopes the item to that specific tenant.
   *
   * @generated from field: string tenant = 7;
   */
  tenant: string;

  /**
   * Definitions of the fields that users can or cannot set when creating a resource from this catalog item.
   *
   * @generated from field: repeated osac.private.v1.FieldDefinition field_definitions = 8;
   */
  fieldDefinitions: FieldDefinition[];
};

/**
 * Describes the message osac.private.v1.ClusterCatalogItem.
 * Use `create(ClusterCatalogItemSchema)` to create a new message.
 */
export const ClusterCatalogItemSchema: GenMessage<ClusterCatalogItem> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_catalog_item_type, 0);

/**
 * Reference to a ClusterCatalogItem resource.
 *
 * @generated from message osac.private.v1.ClusterCatalogItemReference
 */
export type ClusterCatalogItemReference = Message<"osac.private.v1.ClusterCatalogItemReference"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string project = 3;
   */
  project: string;

  /**
   * @generated from field: bool shared = 4;
   */
  shared: boolean;
};

/**
 * Describes the message osac.private.v1.ClusterCatalogItemReference.
 * Use `create(ClusterCatalogItemReferenceSchema)` to create a new message.
 */
export const ClusterCatalogItemReferenceSchema: GenMessage<ClusterCatalogItemReference> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_catalog_item_type, 1);

