//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/cluster_template_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Any } from "../../../google/protobuf/any_pb";
import { file_google_protobuf_any } from "../../../google/protobuf/any_pb";
import type { ClusterNetwork } from "./cluster_type_pb";
import { file_osac_private_v1_cluster_type } from "./cluster_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/cluster_template_type.proto.
 */
export const file_osac_private_v1_cluster_template_type: GenFile = /*@__PURE__*/
  fileDesc("Citvc2FjL3ByaXZhdGUvdjEvY2x1c3Rlcl90ZW1wbGF0ZV90eXBlLnByb3RvEg9vc2FjLnByaXZhdGUudjEimQMKD0NsdXN0ZXJUZW1wbGF0ZRIKCgJpZBgBIAEoCRIrCghtZXRhZGF0YRgCIAEoCzIZLm9zYWMucHJpdmF0ZS52MS5NZXRhZGF0YRINCgV0aXRsZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRJHCgpwYXJhbWV0ZXJzGAUgAygLMjMub3NhYy5wcml2YXRlLnYxLkNsdXN0ZXJUZW1wbGF0ZVBhcmFtZXRlckRlZmluaXRpb24SQQoJbm9kZV9zZXRzGAYgAygLMi4ub3NhYy5wcml2YXRlLnYxLkNsdXN0ZXJUZW1wbGF0ZS5Ob2RlU2V0c0VudHJ5EkMKDXNwZWNfZGVmYXVsdHMYByABKAsyLC5vc2FjLnByaXZhdGUudjEuQ2x1c3RlclRlbXBsYXRlU3BlY0RlZmF1bHRzGlgKDU5vZGVTZXRzRW50cnkSCwoDa2V5GAEgASgJEjYKBXZhbHVlGAIgASgLMicub3NhYy5wcml2YXRlLnYxLkNsdXN0ZXJUZW1wbGF0ZU5vZGVTZXQ6AjgBIp0BCiJDbHVzdGVyVGVtcGxhdGVQYXJhbWV0ZXJEZWZpbml0aW9uEgwKBG5hbWUYASABKAkSDQoFdGl0bGUYAiABKAkSEwoLZGVzY3JpcHRpb24YAyABKAkSEAoIcmVxdWlyZWQYBCABKAgSDAoEdHlwZRgFIAEoCRIlCgdkZWZhdWx0GAYgASgLMhQuZ29vZ2xlLnByb3RvYnVmLkFueSI5ChZDbHVzdGVyVGVtcGxhdGVOb2RlU2V0EhEKCWhvc3RfdHlwZRgBIAEoCRIMCgRzaXplGAIgASgFIugBChtDbHVzdGVyVGVtcGxhdGVTcGVjRGVmYXVsdHMSGAoLcHVsbF9zZWNyZXQYASABKAlIAIgBARIbCg5zc2hfcHVibGljX2tleRgCIAEoCUgBiAEBEhoKDXJlbGVhc2VfaW1hZ2UYAyABKAlIAogBARI1CgduZXR3b3JrGAQgASgLMh8ub3NhYy5wcml2YXRlLnYxLkNsdXN0ZXJOZXR3b3JrSAOIAQFCDgoMX3B1bGxfc2VjcmV0QhEKD19zc2hfcHVibGljX2tleUIQCg5fcmVsZWFzZV9pbWFnZUIKCghfbmV0d29ya2IGcHJvdG8z", [file_google_protobuf_any, file_osac_private_v1_cluster_type, file_osac_private_v1_metadata_type]);

/**
 * buf:lint:ignore OSAC_OBJECT_SHAPE
 *
 * @generated from message osac.private.v1.ClusterTemplate
 */
export type ClusterTemplate = Message<"osac.private.v1.ClusterTemplate"> & {
  /**
   * Public data.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: repeated osac.private.v1.ClusterTemplateParameterDefinition parameters = 5;
   */
  parameters: ClusterTemplateParameterDefinition[];

  /**
   * @generated from field: map<string, osac.private.v1.ClusterTemplateNodeSet> node_sets = 6;
   */
  nodeSets: { [key: string]: ClusterTemplateNodeSet };

  /**
   * Default values for cluster spec fields. When a user creates a cluster
   * without setting these fields, these values are applied.
   *
   * User-provided spec field values always override these defaults.
   *
   * @generated from field: osac.private.v1.ClusterTemplateSpecDefaults spec_defaults = 7;
   */
  specDefaults?: ClusterTemplateSpecDefaults | undefined;
};

/**
 * Describes the message osac.private.v1.ClusterTemplate.
 * Use `create(ClusterTemplateSchema)` to create a new message.
 */
export const ClusterTemplateSchema: GenMessage<ClusterTemplate> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_template_type, 0);

/**
 * @generated from message osac.private.v1.ClusterTemplateParameterDefinition
 */
export type ClusterTemplateParameterDefinition = Message<"osac.private.v1.ClusterTemplateParameterDefinition"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: bool required = 4;
   */
  required: boolean;

  /**
   * @generated from field: string type = 5;
   */
  type: string;

  /**
   * @generated from field: google.protobuf.Any default = 6;
   */
  default?: Any | undefined;
};

/**
 * Describes the message osac.private.v1.ClusterTemplateParameterDefinition.
 * Use `create(ClusterTemplateParameterDefinitionSchema)` to create a new message.
 */
export const ClusterTemplateParameterDefinitionSchema: GenMessage<ClusterTemplateParameterDefinition> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_template_type, 1);

/**
 * @generated from message osac.private.v1.ClusterTemplateNodeSet
 */
export type ClusterTemplateNodeSet = Message<"osac.private.v1.ClusterTemplateNodeSet"> & {
  /**
   * @generated from field: string host_type = 1;
   */
  hostType: string;

  /**
   * @generated from field: int32 size = 2;
   */
  size: number;
};

/**
 * Describes the message osac.private.v1.ClusterTemplateNodeSet.
 * Use `create(ClusterTemplateNodeSetSchema)` to create a new message.
 */
export const ClusterTemplateNodeSetSchema: GenMessage<ClusterTemplateNodeSet> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_template_type, 2);

/**
 * Default values for cluster spec fields.
 *
 * @generated from message osac.private.v1.ClusterTemplateSpecDefaults
 */
export type ClusterTemplateSpecDefaults = Message<"osac.private.v1.ClusterTemplateSpecDefaults"> & {
  /**
   * Default pull secret for authenticating to container image repositories.
   *
   * @generated from field: optional string pull_secret = 1;
   */
  pullSecret?: string | undefined;

  /**
   * Default SSH public key installed on cluster worker nodes.
   *
   * @generated from field: optional string ssh_public_key = 2;
   */
  sshPublicKey?: string | undefined;

  /**
   * Default OCP release image URL.
   *
   * @generated from field: optional string release_image = 3;
   */
  releaseImage?: string | undefined;

  /**
   * Default cluster networking configuration.
   *
   * @generated from field: optional osac.private.v1.ClusterNetwork network = 4;
   */
  network?: ClusterNetwork | undefined;
};

/**
 * Describes the message osac.private.v1.ClusterTemplateSpecDefaults.
 * Use `create(ClusterTemplateSpecDefaultsSchema)` to create a new message.
 */
export const ClusterTemplateSpecDefaultsSchema: GenMessage<ClusterTemplateSpecDefaults> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_cluster_template_type, 3);

