//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/compute_instance_template_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Any } from "../../../google/protobuf/any_pb";
import { file_google_protobuf_any } from "../../../google/protobuf/any_pb";
import type { ComputeInstanceDisk, ComputeInstanceImage } from "./compute_instance_type_pb";
import { file_osac_private_v1_compute_instance_type } from "./compute_instance_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/compute_instance_template_type.proto.
 */
export const file_osac_private_v1_compute_instance_template_type: GenFile = /*@__PURE__*/
  fileDesc("CjRvc2FjL3ByaXZhdGUvdjEvY29tcHV0ZV9pbnN0YW5jZV90ZW1wbGF0ZV90eXBlLnByb3RvEg9vc2FjLnByaXZhdGUudjEilAIKF0NvbXB1dGVJbnN0YW5jZVRlbXBsYXRlEgoKAmlkGAEgASgJEisKCG1ldGFkYXRhGAIgASgLMhkub3NhYy5wcml2YXRlLnYxLk1ldGFkYXRhEg0KBXRpdGxlGAMgASgJEhMKC2Rlc2NyaXB0aW9uGAQgASgJEk8KCnBhcmFtZXRlcnMYBSADKAsyOy5vc2FjLnByaXZhdGUudjEuQ29tcHV0ZUluc3RhbmNlVGVtcGxhdGVQYXJhbWV0ZXJEZWZpbml0aW9uEksKDXNwZWNfZGVmYXVsdHMYBiABKAsyNC5vc2FjLnByaXZhdGUudjEuQ29tcHV0ZUluc3RhbmNlVGVtcGxhdGVTcGVjRGVmYXVsdHMipQEKKkNvbXB1dGVJbnN0YW5jZVRlbXBsYXRlUGFyYW1ldGVyRGVmaW5pdGlvbhIMCgRuYW1lGAEgASgJEg0KBXRpdGxlGAIgASgJEhMKC2Rlc2NyaXB0aW9uGAMgASgJEhAKCHJlcXVpcmVkGAQgASgIEgwKBHR5cGUYBSABKAkSJQoHZGVmYXVsdBgGIAEoCzIULmdvb2dsZS5wcm90b2J1Zi5Bbnki1wIKI0NvbXB1dGVJbnN0YW5jZVRlbXBsYXRlU3BlY0RlZmF1bHRzEjkKBWltYWdlGAMgASgLMiUub3NhYy5wcml2YXRlLnYxLkNvbXB1dGVJbnN0YW5jZUltYWdlSACIAQESPAoJYm9vdF9kaXNrGAQgASgLMiQub3NhYy5wcml2YXRlLnYxLkNvbXB1dGVJbnN0YW5jZURpc2tIAYgBARIZCgxydW5fc3RyYXRlZ3kYBSABKAlIAogBARIaCg1pbnN0YW5jZV90eXBlGAYgASgJSAOIAQESFwoKaXNfd2luZG93cxgHIAEoCEgEiAEBQggKBl9pbWFnZUIMCgpfYm9vdF9kaXNrQg8KDV9ydW5fc3RyYXRlZ3lCEAoOX2luc3RhbmNlX3R5cGVCDQoLX2lzX3dpbmRvd3NKBAgBEAJKBAgCEANSBWNvcmVzUgptZW1vcnlfZ2liYgZwcm90bzM", [file_google_protobuf_any, file_osac_private_v1_compute_instance_type, file_osac_private_v1_metadata_type]);

/**
 * buf:lint:ignore OSAC_OBJECT_SHAPE
 *
 * @generated from message osac.private.v1.ComputeInstanceTemplate
 */
export type ComputeInstanceTemplate = Message<"osac.private.v1.ComputeInstanceTemplate"> & {
  /**
   * Public data.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * @generated from field: repeated osac.private.v1.ComputeInstanceTemplateParameterDefinition parameters = 5;
   */
  parameters: ComputeInstanceTemplateParameterDefinition[];

  /**
   * Default values for compute instance spec fields. When a user creates a
   * compute instance without setting these fields, these values are applied.
   *
   * User-provided spec field values always override these defaults.
   *
   * @generated from field: osac.private.v1.ComputeInstanceTemplateSpecDefaults spec_defaults = 6;
   */
  specDefaults?: ComputeInstanceTemplateSpecDefaults | undefined;
};

/**
 * Describes the message osac.private.v1.ComputeInstanceTemplate.
 * Use `create(ComputeInstanceTemplateSchema)` to create a new message.
 */
export const ComputeInstanceTemplateSchema: GenMessage<ComputeInstanceTemplate> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_compute_instance_template_type, 0);

/**
 * @generated from message osac.private.v1.ComputeInstanceTemplateParameterDefinition
 */
export type ComputeInstanceTemplateParameterDefinition = Message<"osac.private.v1.ComputeInstanceTemplateParameterDefinition"> & {
  /**
   * @generated from field: string name = 1;
   */
  name: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string description = 3;
   */
  description: string;

  /**
   * @generated from field: bool required = 4;
   */
  required: boolean;

  /**
   * @generated from field: string type = 5;
   */
  type: string;

  /**
   * @generated from field: google.protobuf.Any default = 6;
   */
  default?: Any | undefined;
};

/**
 * Describes the message osac.private.v1.ComputeInstanceTemplateParameterDefinition.
 * Use `create(ComputeInstanceTemplateParameterDefinitionSchema)` to create a new message.
 */
export const ComputeInstanceTemplateParameterDefinitionSchema: GenMessage<ComputeInstanceTemplateParameterDefinition> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_compute_instance_template_type, 1);

/**
 * Default values for compute instance spec fields.
 *
 * @generated from message osac.private.v1.ComputeInstanceTemplateSpecDefaults
 */
export type ComputeInstanceTemplateSpecDefaults = Message<"osac.private.v1.ComputeInstanceTemplateSpecDefaults"> & {
  /**
   * Default image configuration.
   *
   * @generated from field: optional osac.private.v1.ComputeInstanceImage image = 3;
   */
  image?: ComputeInstanceImage | undefined;

  /**
   * Default boot disk configuration.
   *
   * @generated from field: optional osac.private.v1.ComputeInstanceDisk boot_disk = 4;
   */
  bootDisk?: ComputeInstanceDisk | undefined;

  /**
   * Default run strategy.
   *
   * @generated from field: optional string run_strategy = 5;
   */
  runStrategy?: string | undefined;

  /**
   * Default instance type name. Specifies the default compute configuration for instances
   * created from this template.
   *
   * @generated from field: optional string instance_type = 6;
   */
  instanceType?: string | undefined;

  /**
   * Default guest OS type. When true, the VM runs Windows. When false or omitted, the VM runs Linux.
   *
   * @generated from field: optional bool is_windows = 7;
   */
  isWindows?: boolean | undefined;
};

/**
 * Describes the message osac.private.v1.ComputeInstanceTemplateSpecDefaults.
 * Use `create(ComputeInstanceTemplateSpecDefaultsSchema)` to create a new message.
 */
export const ComputeInstanceTemplateSpecDefaultsSchema: GenMessage<ComputeInstanceTemplateSpecDefaults> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_compute_instance_template_type, 2);

