//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/compute_instance_catalog_item_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { FieldDefinition } from "./field_definition_type_pb";
import { file_osac_private_v1_field_definition_type } from "./field_definition_type_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/compute_instance_catalog_item_type.proto.
 */
export const file_osac_private_v1_compute_instance_catalog_item_type: GenFile = /*@__PURE__*/
  fileDesc("Cjhvc2FjL3ByaXZhdGUvdjEvY29tcHV0ZV9pbnN0YW5jZV9jYXRhbG9nX2l0ZW1fdHlwZS5wcm90bxIPb3NhYy5wcml2YXRlLnYxIusBChpDb21wdXRlSW5zdGFuY2VDYXRhbG9nSXRlbRIKCgJpZBgBIAEoCRIrCghtZXRhZGF0YRgCIAEoCzIZLm9zYWMucHJpdmF0ZS52MS5NZXRhZGF0YRINCgV0aXRsZRgDIAEoCRITCgtkZXNjcmlwdGlvbhgEIAEoCRIQCgh0ZW1wbGF0ZRgFIAEoCRIRCglwdWJsaXNoZWQYBiABKAgSDgoGdGVuYW50GAcgASgJEjsKEWZpZWxkX2RlZmluaXRpb25zGAggAygLMiAub3NhYy5wcml2YXRlLnYxLkZpZWxkRGVmaW5pdGlvbmIGcHJvdG8z", [file_osac_private_v1_field_definition_type, file_osac_private_v1_metadata_type]);

/**
 * A compute instance catalog item defines a curated infrastructure offering that references an underlying compute
 * instance template. Admins control which fields users can set, enforce defaults, and validate input via JSON Schema.
 *
 * buf:lint:ignore OSAC_OBJECT_SHAPE
 *
 * @generated from message osac.private.v1.ComputeInstanceCatalogItem
 */
export type ComputeInstanceCatalogItem = Message<"osac.private.v1.ComputeInstanceCatalogItem"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the catalog item, suitable for displaying in one single line on a UI or CLI.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the catalog item, using Markdown format.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Identifier of the underlying compute instance template that this catalog item references.
   *
   * @generated from field: string template = 5;
   */
  template: string;

  /**
   * Whether this catalog item is visible in the public API.
   *
   * @generated from field: bool published = 6;
   */
  published: boolean;

  /**
   * Tenant scope for this catalog item. An empty string means the item is global and visible to all tenants.
   *
   * @generated from field: string tenant = 7;
   */
  tenant: string;

  /**
   * Definitions of the fields that users can or cannot set when creating a resource from this catalog item.
   *
   * @generated from field: repeated osac.private.v1.FieldDefinition field_definitions = 8;
   */
  fieldDefinitions: FieldDefinition[];
};

/**
 * Describes the message osac.private.v1.ComputeInstanceCatalogItem.
 * Use `create(ComputeInstanceCatalogItemSchema)` to create a new message.
 */
export const ComputeInstanceCatalogItemSchema: GenMessage<ComputeInstanceCatalogItem> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_compute_instance_catalog_item_type, 0);

