//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/external_ip_attribution_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import type { BareMetalInstanceLocalReference } from "./baremetal_instance_type_pb";
import { file_osac_private_v1_baremetal_instance_type } from "./baremetal_instance_type_pb";
import type { ClusterLocalReference } from "./cluster_type_pb";
import { file_osac_private_v1_cluster_type } from "./cluster_type_pb";
import type { ComputeInstanceLocalReference } from "./compute_instance_type_pb";
import { file_osac_private_v1_compute_instance_type } from "./compute_instance_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/external_ip_attribution_type.proto.
 */
export const file_osac_private_v1_external_ip_attribution_type: GenFile = /*@__PURE__*/
  fileDesc("CjJvc2FjL3ByaXZhdGUvdjEvZXh0ZXJuYWxfaXBfYXR0cmlidXRpb25fdHlwZS5wcm90bxIPb3NhYy5wcml2YXRlLnYxIuEFChVFeHRlcm5hbElQQXR0cmlidXRpb24SSgoQY29tcHV0ZV9pbnN0YW5jZRgBIAEoCzIuLm9zYWMucHJpdmF0ZS52MS5Db21wdXRlSW5zdGFuY2VMb2NhbFJlZmVyZW5jZUgAEjkKB2NsdXN0ZXIYAiABKAsyJi5vc2FjLnByaXZhdGUudjEuQ2x1c3RlckxvY2FsUmVmZXJlbmNlSAASTgoSYmFyZW1ldGFsX2luc3RhbmNlGAMgASgLMjAub3NhYy5wcml2YXRlLnYxLkJhcmVNZXRhbEluc3RhbmNlTG9jYWxSZWZlcmVuY2VIABJJCghlbmRwb2ludBgEIAEoDjItLm9zYWMucHJpdmF0ZS52MS5FeHRlcm5hbElQQXR0YWNobWVudEVuZHBvaW50Qgi6SAWCAQIQATqUA7pIigMa3gEKIWV4dGVybmFsX2lwX2F0dHJpYnV0aW9uX3RhcmdldF9pZBIsdGhlIHNlbGVjdGVkIHRhcmdldCBtdXN0IGhhdmUgYSBub24tZW1wdHkgaWQaigFoYXModGhpcy5jb21wdXRlX2luc3RhbmNlKSA/IHRoaXMuY29tcHV0ZV9pbnN0YW5jZS5pZCAhPSAnJyA6IGhhcyh0aGlzLmNsdXN0ZXIpID8gdGhpcy5jbHVzdGVyLmlkICE9ICcnIDogdGhpcy5iYXJlbWV0YWxfaW5zdGFuY2UuaWQgIT0gJycapgEKIGV4dGVybmFsX2lwX2F0dHJpYnV0aW9uX2VuZHBvaW50Ei1lbmRwb2ludCBpcyByZXF1aXJlZCBvbmx5IGZvciBjbHVzdGVyIHRhcmdldHMaU2hhcyh0aGlzLmNsdXN0ZXIpID8gKHRoaXMuZW5kcG9pbnQgPT0gMSB8fCB0aGlzLmVuZHBvaW50ID09IDIpIDogdGhpcy5lbmRwb2ludCA9PSAwirUYAggBQg8KBnRhcmdldBIFukgCCAEqpQEKHEV4dGVybmFsSVBBdHRhY2htZW50RW5kcG9pbnQSLworRVhURVJOQUxfSVBfQVRUQUNITUVOVF9FTkRQT0lOVF9VTlNQRUNJRklFRBAAEicKI0VYVEVSTkFMX0lQX0FUVEFDSE1FTlRfRU5EUE9JTlRfQVBJEAESKwonRVhURVJOQUxfSVBfQVRUQUNITUVOVF9FTkRQT0lOVF9JTkdSRVNTEAJCFIq1GBASDm9zYWMucHVibGljLnYxYgZwcm90bzM", [file_buf_validate_validate, file_cleanapi_cleanapi, file_osac_private_v1_baremetal_instance_type, file_osac_private_v1_cluster_type, file_osac_private_v1_compute_instance_type]);

/**
 * Settled target attribution for an ExternalIP.
 *
 * @generated from message osac.private.v1.ExternalIPAttribution
 */
export type ExternalIPAttribution = Message<"osac.private.v1.ExternalIPAttribution"> & {
  /**
   * @generated from oneof osac.private.v1.ExternalIPAttribution.target
   */
  target: {
    /**
     * ComputeInstance to which the ExternalIP is attached.
     *
     * @generated from field: osac.private.v1.ComputeInstanceLocalReference compute_instance = 1;
     */
    value: ComputeInstanceLocalReference;
    case: "computeInstance";
  } | {
    /**
     * Cluster to which the ExternalIP is attached.
     *
     * @generated from field: osac.private.v1.ClusterLocalReference cluster = 2;
     */
    value: ClusterLocalReference;
    case: "cluster";
  } | {
    /**
     * BareMetalInstance to which the ExternalIP is attached.
     *
     * @generated from field: osac.private.v1.BareMetalInstanceLocalReference baremetal_instance = 3;
     */
    value: BareMetalInstanceLocalReference;
    case: "baremetalInstance";
  } | { case: undefined; value?: undefined };

  /**
   * Cluster endpoint targeted by the attachment. It must be UNSPECIFIED for non-cluster targets.
   *
   * @generated from field: osac.private.v1.ExternalIPAttachmentEndpoint endpoint = 4;
   */
  endpoint: ExternalIPAttachmentEndpoint;
};

/**
 * Describes the message osac.private.v1.ExternalIPAttribution.
 * Use `create(ExternalIPAttributionSchema)` to create a new message.
 */
export const ExternalIPAttributionSchema: GenMessage<ExternalIPAttribution> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_external_ip_attribution_type, 0);

/**
 * Endpoint targeted by an ExternalIPAttachment for a cluster.
 *
 * @generated from enum osac.private.v1.ExternalIPAttachmentEndpoint
 */
export enum ExternalIPAttachmentEndpoint {
  /**
   * The endpoint has not been specified.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_ENDPOINT_UNSPECIFIED = 0;
   */
  EXTERNAL_IP_ATTACHMENT_ENDPOINT_UNSPECIFIED = 0,

  /**
   * The cluster API server endpoint.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_ENDPOINT_API = 1;
   */
  EXTERNAL_IP_ATTACHMENT_ENDPOINT_API = 1,

  /**
   * The cluster ingress endpoint.
   *
   * @generated from enum value: EXTERNAL_IP_ATTACHMENT_ENDPOINT_INGRESS = 2;
   */
  EXTERNAL_IP_ATTACHMENT_ENDPOINT_INGRESS = 2,
}

/**
 * Describes the enum osac.private.v1.ExternalIPAttachmentEndpoint.
 */
export const ExternalIPAttachmentEndpointSchema: GenEnum<ExternalIPAttachmentEndpoint> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_external_ip_attribution_type, 0);

