//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/secret_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import { file_cleanapi_cleanapi } from "../../../cleanapi/cleanapi_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/secret_type.proto.
 */
export const file_osac_private_v1_secret_type: GenFile = /*@__PURE__*/
  fileDesc("CiFvc2FjL3ByaXZhdGUvdjEvc2VjcmV0X3R5cGUucHJvdG8SD29zYWMucHJpdmF0ZS52MSKWAwoGU2VjcmV0EgoKAmlkGAEgASgJEisKCG1ldGFkYXRhGAIgASgLMhkub3NhYy5wcml2YXRlLnYxLk1ldGFkYXRhEj0KBGRhdGEYAyADKAsyIS5vc2FjLnByaXZhdGUudjEuU2VjcmV0LkRhdGFFbnRyeUIMukgJmgEGIgRyAhABEjcKB2JhY2tlbmQYBCABKA4yHi5vc2FjLnByaXZhdGUudjEuU2VjcmV0QmFja2VuZEIGirUYAggBEkUKC2Nvb3JkaW5hdGVzGAUgAygLMigub3NhYy5wcml2YXRlLnYxLlNlY3JldC5Db29yZGluYXRlc0VudHJ5QgaKtRgCCAESMwoEdHlwZRgGIAEoDjIbLm9zYWMucHJpdmF0ZS52MS5TZWNyZXRUeXBlQgi6SAWCAQIQARorCglEYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgMOgI4ARoyChBDb29yZGluYXRlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiMAoUU2VjcmV0TG9jYWxSZWZlcmVuY2USCgoCaWQYASABKAkSDAoEbmFtZRgCIAEoCSqsAQoKU2VjcmV0VHlwZRIbChdTRUNSRVRfVFlQRV9VTlNQRUNJRklFRBAAEhsKF1NFQ1JFVF9UWVBFX1BVTExfU0VDUkVUEAESGgoWU0VDUkVUX1RZUEVfS1VCRUNPTkZJRxACEhkKFVNFQ1JFVF9UWVBFX1VTRVJfREFUQRADEhYKElNFQ1JFVF9UWVBFX09QQVFVRRAEEhUKEVNFQ1JFVF9UWVBFX1ZBTFVFEAUqaQoNU2VjcmV0QmFja2VuZBIeChpTRUNSRVRfQkFDS0VORF9VTlNQRUNJRklFRBAAEhgKFFNFQ1JFVF9CQUNLRU5EX1ZBVUxUEAESFgoSU0VDUkVUX0JBQ0tFTkRfSFVCEAIaBoq1GAIIAUIUirUYEBIOb3NhYy5wdWJsaWMudjFiBnByb3RvMw", [file_buf_validate_validate, file_cleanapi_cleanapi, file_osac_private_v1_metadata_type]);

/**
 * Represents a secret containing typed or opaque key-value data.
 *
 * Secrets store sensitive information such as TLS certificates, pull secrets, and credentials. Each secret holds a map
 * of named binary values.
 *
 * Secrets are scoped to a tenant and can be referenced by other resources that require sensitive configuration data.
 *
 * buf:lint:ignore OSAC_OBJECT_SHAPE
 *
 * @generated from message osac.private.v1.Secret
 */
export type Secret = Message<"osac.private.v1.Secret"> & {
  /**
   * Unique identifier of the secret.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the secret.
   *
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Opaque key-value data. Each key identifies a named entry (for example, `crt` or `key`) and the
   * corresponding value is the raw secret material. Populated in Get responses; omitted from List and
   * mutating responses.
   *
   * @generated from field: map<string, bytes> data = 3;
   */
  data: { [key: string]: Uint8Array };

  /**
   * Storage backend used to manage this secret.
   * Optionally references a storage backend (such as Vault or Hub) for external secret.
   *
   * @generated from field: osac.private.v1.SecretBackend backend = 4;
   */
  backend: SecretBackend;

  /**
   * Backend-specific location metadata used to resolve the secret in the external system.
   *
   * @generated from field: map<string, string> coordinates = 5;
   */
  coordinates: { [key: string]: string };

  /**
   * Type of data stored in the secret.
   *
   * @generated from field: osac.private.v1.SecretType type = 6;
   */
  type: SecretType;
};

/**
 * Describes the message osac.private.v1.Secret.
 * Use `create(SecretSchema)` to create a new message.
 */
export const SecretSchema: GenMessage<Secret> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_secret_type, 0);

/**
 * Local reference to a Secret resource.
 *
 * @generated from message osac.private.v1.SecretLocalReference
 */
export type SecretLocalReference = Message<"osac.private.v1.SecretLocalReference"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message osac.private.v1.SecretLocalReference.
 * Use `create(SecretLocalReferenceSchema)` to create a new message.
 */
export const SecretLocalReferenceSchema: GenMessage<SecretLocalReference> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_secret_type, 1);

/**
 * The type of data stored in a secret.
 *
 * @generated from enum osac.private.v1.SecretType
 */
export enum SecretType {
  /**
   * The secret type is not specified. The service treats an unspecified type as opaque when creating a secret.
   *
   * @generated from enum value: SECRET_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * A Kubernetes-compatible container registry pull secret. Requires a `.dockerconfigjson` data key.
   *
   * @generated from enum value: SECRET_TYPE_PULL_SECRET = 1;
   */
  PULL_SECRET = 1,

  /**
   * A Kubernetes client configuration. Requires a `kubeconfig` data key.
   *
   * @generated from enum value: SECRET_TYPE_KUBECONFIG = 2;
   */
  KUBECONFIG = 2,

  /**
   * Cloud-init or other instance user data. Requires a `userdata` data key.
   *
   * @generated from enum value: SECRET_TYPE_USER_DATA = 3;
   */
  USER_DATA = 3,

  /**
   * An opaque secret with no required data keys.
   *
   * @generated from enum value: SECRET_TYPE_OPAQUE = 4;
   */
  OPAQUE = 4,

  /**
   * Represents a single value of any kind. Requires a `value` data key.
   *
   * @generated from enum value: SECRET_TYPE_VALUE = 5;
   */
  VALUE = 5,
}

/**
 * Describes the enum osac.private.v1.SecretType.
 */
export const SecretTypeSchema: GenEnum<SecretType> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_secret_type, 0);

/**
 * Storage backends for secret management.
 *
 * @generated from enum osac.private.v1.SecretBackend
 */
export enum SecretBackend {
  /**
   * Backend is unknown or the secret is stored inline.
   *
   * @generated from enum value: SECRET_BACKEND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Secret is managed by HashiCorp Vault.
   *
   * @generated from enum value: SECRET_BACKEND_VAULT = 1;
   */
  VAULT = 1,

  /**
   * Secret is managed by the OSAC Hub.
   *
   * @generated from enum value: SECRET_BACKEND_HUB = 2;
   */
  HUB = 2,
}

/**
 * Describes the enum osac.private.v1.SecretBackend.
 */
export const SecretBackendSchema: GenEnum<SecretBackend> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_secret_type, 1);

