//
// Copyright (c) 2026 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/private/v1/secret_type.proto (package osac.private.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_private_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/private/v1/secret_type.proto.
 */
export const file_osac_private_v1_secret_type: GenFile = /*@__PURE__*/
  fileDesc("CiFvc2FjL3ByaXZhdGUvdjEvc2VjcmV0X3R5cGUucHJvdG8SD29zYWMucHJpdmF0ZS52MSKbAQoGU2VjcmV0EgoKAmlkGAEgASgJEisKCG1ldGFkYXRhGAIgASgLMhkub3NhYy5wcml2YXRlLnYxLk1ldGFkYXRhEikKBHNwZWMYAyABKAsyGy5vc2FjLnByaXZhdGUudjEuU2VjcmV0U3BlYxItCgZzdGF0dXMYBCABKAsyHS5vc2FjLnByaXZhdGUudjEuU2VjcmV0U3RhdHVzIpYCCgpTZWNyZXRTcGVjEjMKBGRhdGEYASADKAsyJS5vc2FjLnByaXZhdGUudjEuU2VjcmV0U3BlYy5EYXRhRW50cnkSLwoHYmFja2VuZBgCIAEoDjIeLm9zYWMucHJpdmF0ZS52MS5TZWNyZXRCYWNrZW5kEkEKC2Nvb3JkaW5hdGVzGAMgAygLMiwub3NhYy5wcml2YXRlLnYxLlNlY3JldFNwZWMuQ29vcmRpbmF0ZXNFbnRyeRorCglEYXRhRW50cnkSCwoDa2V5GAEgASgJEg0KBXZhbHVlGAIgASgMOgI4ARoyChBDb29yZGluYXRlc0VudHJ5EgsKA2tleRgBIAEoCRINCgV2YWx1ZRgCIAEoCToCOAEiiwEKDFNlY3JldFN0YXR1cxJGCg1yZXNvbHZlZF9kYXRhGAEgAygLMi8ub3NhYy5wcml2YXRlLnYxLlNlY3JldFN0YXR1cy5SZXNvbHZlZERhdGFFbnRyeRozChFSZXNvbHZlZERhdGFFbnRyeRILCgNrZXkYASABKAkSDQoFdmFsdWUYAiABKAw6AjgBKmEKDVNlY3JldEJhY2tlbmQSHgoaU0VDUkVUX0JBQ0tFTkRfVU5TUEVDSUZJRUQQABIYChRTRUNSRVRfQkFDS0VORF9WQVVMVBABEhYKElNFQ1JFVF9CQUNLRU5EX0hVQhACYgZwcm90bzM", [file_osac_private_v1_metadata_type]);

/**
 * Represents a secret containing opaque key-value data.
 *
 * Secrets store sensitive information such as TLS certificates, pull secrets, and credentials. Each secret holds a map
 * of named binary values and optionally references a storage backend (such as Vault or Hub) for external secret
 * management. The `coordinates` field carries backend-specific location metadata used to resolve the secret in the
 * external system.
 *
 * @generated from message osac.private.v1.Secret
 */
export type Secret = Message<"osac.private.v1.Secret"> & {
  /**
   * Unique identifier of the secret.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Metadata of the secret.
   *
   * @generated from field: osac.private.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Desired state of the secret.
   *
   * @generated from field: osac.private.v1.SecretSpec spec = 3;
   */
  spec?: SecretSpec | undefined;

  /**
   * Observed state of the secret, populated by the server.
   *
   * @generated from field: osac.private.v1.SecretStatus status = 4;
   */
  status?: SecretStatus | undefined;
};

/**
 * Describes the message osac.private.v1.Secret.
 * Use `create(SecretSchema)` to create a new message.
 */
export const SecretSchema: GenMessage<Secret> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_secret_type, 0);

/**
 * Desired state of a secret.
 *
 * @generated from message osac.private.v1.SecretSpec
 */
export type SecretSpec = Message<"osac.private.v1.SecretSpec"> & {
  /**
   * Opaque key-value data. Each key identifies a named entry (for example, `crt` or `key`) and the
   * corresponding value is the raw secret material.
   *
   * @generated from field: map<string, bytes> data = 1;
   */
  data: { [key: string]: Uint8Array };

  /**
   * Storage backend used to manage this secret.
   *
   * @generated from field: osac.private.v1.SecretBackend backend = 2;
   */
  backend: SecretBackend;

  /**
   * Backend-specific location metadata.
   *
   * @generated from field: map<string, string> coordinates = 3;
   */
  coordinates: { [key: string]: string };
};

/**
 * Describes the message osac.private.v1.SecretSpec.
 * Use `create(SecretSpecSchema)` to create a new message.
 */
export const SecretSpecSchema: GenMessage<SecretSpec> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_secret_type, 1);

/**
 * Observed state of a secret, populated by the server.
 *
 * @generated from message osac.private.v1.SecretStatus
 */
export type SecretStatus = Message<"osac.private.v1.SecretStatus"> & {
  /**
   * The secret's resolved key-value data. Present in Get responses; omitted from List responses.
   *
   * @generated from field: map<string, bytes> resolved_data = 1;
   */
  resolvedData: { [key: string]: Uint8Array };
};

/**
 * Describes the message osac.private.v1.SecretStatus.
 * Use `create(SecretStatusSchema)` to create a new message.
 */
export const SecretStatusSchema: GenMessage<SecretStatus> = /*@__PURE__*/
  messageDesc(file_osac_private_v1_secret_type, 2);

/**
 * Storage backends for secret management.
 *
 * @generated from enum osac.private.v1.SecretBackend
 */
export enum SecretBackend {
  /**
   * Backend is unknown or the secret is stored inline.
   *
   * @generated from enum value: SECRET_BACKEND_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Secret is managed by HashiCorp Vault.
   *
   * @generated from enum value: SECRET_BACKEND_VAULT = 1;
   */
  VAULT = 1,

  /**
   * Secret is managed by the OSAC Hub.
   *
   * @generated from enum value: SECRET_BACKEND_HUB = 2;
   */
  HUB = 2,
}

/**
 * Describes the enum osac.private.v1.SecretBackend.
 */
export const SecretBackendSchema: GenEnum<SecretBackend> = /*@__PURE__*/
  enumDesc(file_osac_private_v1_secret_type, 0);

