apiVersion: v1
kind: Service
metadata:
  name: osac
  namespace: osac-dev
spec:
  selector:
    app: osac
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
---
apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: osac
  namespace: osac-dev
spec:
  to:
    kind: Service
    name: osac
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
