//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/add_on_operator_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import { file_buf_validate_validate } from "../../../buf/validate/validate_pb";
import type { Metadata } from "./metadata_type_pb";
import { file_osac_public_v1_metadata_type } from "./metadata_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/add_on_operator_type.proto.
 */
export const file_osac_public_v1_add_on_operator_type: GenFile = /*@__PURE__*/
  fileDesc("Cilvc2FjL3B1YmxpYy92MS9hZGRfb25fb3BlcmF0b3JfdHlwZS5wcm90bxIOb3NhYy5wdWJsaWMudjEi0AIKDUFkZE9uT3BlcmF0b3ISCgoCaWQYASABKAkSKgoIbWV0YWRhdGEYAiABKAsyGC5vc2FjLnB1YmxpYy52MS5NZXRhZGF0YRIWCgV0aXRsZRgDIAEoCUIHukgEcgIQARITCgtkZXNjcmlwdGlvbhgEIAEoCRIXCg9taW5fb2NwX3ZlcnNpb24YBSABKAkSFwoPbWF4X29jcF92ZXJzaW9uGAYgASgJEj8KCmV4Y2x1c2lvbnMYByADKAsyKy5vc2FjLnB1YmxpYy52MS5BZGRPbk9wZXJhdG9yTG9jYWxSZWZlcmVuY2USQQoMZGVwZW5kZW5jaWVzGAggAygLMisub3NhYy5wdWJsaWMudjEuQWRkT25PcGVyYXRvckxvY2FsUmVmZXJlbmNlEhYKCXB1Ymxpc2hlZBgJIAEoCEgAiAEBQgwKCl9wdWJsaXNoZWQiUwoWQWRkT25PcGVyYXRvclJlZmVyZW5jZRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJEg8KB3Byb2plY3QYAyABKAkSDgoGc2hhcmVkGAQgASgIIjcKG0FkZE9uT3BlcmF0b3JMb2NhbFJlZmVyZW5jZRIKCgJpZBgBIAEoCRIMCgRuYW1lGAIgASgJYgZwcm90bzM", [file_buf_validate_validate, file_osac_public_v1_metadata_type]);

/**
 * An add-on operator represents a platform-supported OLM operator that can be installed on CaaS clusters. The resource
 * stores metadata for validation and display; OLM subscription details remain in the Ansible role.
 *
 * buf:lint:ignore OSAC_OBJECT_SHAPE
 *
 * @generated from message osac.public.v1.AddOnOperator
 */
export type AddOnOperator = Message<"osac.public.v1.AddOnOperator"> & {
  /**
   * Unique identifier of the add-on operator.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: osac.public.v1.Metadata metadata = 2;
   */
  metadata?: Metadata | undefined;

  /**
   * Human friendly short description of the add-on operator, suitable for displaying in one single line on a UI or CLI.
   *
   * @generated from field: string title = 3;
   */
  title: string;

  /**
   * Human friendly long description of the add-on operator, using Markdown format.
   *
   * @generated from field: string description = 4;
   */
  description: string;

  /**
   * Minimum supported OpenShift version (inclusive SemVer-compatible version). Shorthand such as "4.17" is accepted
   * and interpreted as "4.17.0". Empty means no minimum.
   *
   * @generated from field: string min_ocp_version = 5;
   */
  minOcpVersion: string;

  /**
   * Maximum supported OpenShift version (inclusive SemVer-compatible version). Shorthand such as "4.17" is accepted
   * and interpreted as "4.17.0". Empty means no maximum.
   *
   * @generated from field: string max_ocp_version = 6;
   */
  maxOcpVersion: string;

  /**
   * Other add-on operators that are mutually exclusive with this one. Bidirectional: if A excludes B, ordering a
   * cluster with both A and B is rejected at order time.
   *
   * @generated from field: repeated osac.public.v1.AddOnOperatorLocalReference exclusions = 7;
   */
  exclusions: AddOnOperatorLocalReference[];

  /**
   * Other add-on operators that this one depends on. Dependencies are auto-included in the resolved operator set at
   * order time.
   *
   * @generated from field: repeated osac.public.v1.AddOnOperatorLocalReference dependencies = 8;
   */
  dependencies: AddOnOperatorLocalReference[];

  /**
   * Whether this add-on operator is visible through the public API. Defaults to false; the Cloud Provider Admin
   * publishes operators explicitly after review.
   *
   * @generated from field: optional bool published = 9;
   */
  published?: boolean | undefined;
};

/**
 * Describes the message osac.public.v1.AddOnOperator.
 * Use `create(AddOnOperatorSchema)` to create a new message.
 */
export const AddOnOperatorSchema: GenMessage<AddOnOperator> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_add_on_operator_type, 0);

/**
 * Standard reference to an AddOnOperator resource (used by ClusterCatalogItem and ClusterSpec).
 *
 * @generated from message osac.public.v1.AddOnOperatorReference
 */
export type AddOnOperatorReference = Message<"osac.public.v1.AddOnOperatorReference"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string project = 3;
   */
  project: string;

  /**
   * @generated from field: bool shared = 4;
   */
  shared: boolean;
};

/**
 * Describes the message osac.public.v1.AddOnOperatorReference.
 * Use `create(AddOnOperatorReferenceSchema)` to create a new message.
 */
export const AddOnOperatorReferenceSchema: GenMessage<AddOnOperatorReference> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_add_on_operator_type, 1);

/**
 * Local reference to an AddOnOperator (used within the AddOnOperator message for exclusions and dependencies).
 *
 * @generated from message osac.public.v1.AddOnOperatorLocalReference
 */
export type AddOnOperatorLocalReference = Message<"osac.public.v1.AddOnOperatorLocalReference"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;
};

/**
 * Describes the message osac.public.v1.AddOnOperatorLocalReference.
 * Use `create(AddOnOperatorLocalReferenceSchema)` to create a new message.
 */
export const AddOnOperatorLocalReferenceSchema: GenMessage<AddOnOperatorLocalReference> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_add_on_operator_type, 2);

