//
// Copyright (c) 2025 Red Hat, Inc.
//
// Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
// the License. You may obtain a copy of the License at
//
//   http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
// an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
// specific language governing permissions and limitations under the License.
//

// @generated by protoc-gen-es v2.12.0 with parameter "target=ts"
// @generated from file osac/public/v1/event_type.proto (package osac.public.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv2";
import { enumDesc, fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv2";
import type { Timestamp } from "../../../google/protobuf/timestamp_pb";
import { file_google_protobuf_timestamp } from "../../../google/protobuf/timestamp_pb";
import type { BareMetalInstance } from "./baremetal_instance_type_pb";
import { file_osac_public_v1_baremetal_instance_type } from "./baremetal_instance_type_pb";
import type { ClusterTemplate } from "./cluster_template_type_pb";
import { file_osac_public_v1_cluster_template_type } from "./cluster_template_type_pb";
import type { ClusterVersion } from "./cluster_version_type_pb";
import { file_osac_public_v1_cluster_version_type } from "./cluster_version_type_pb";
import type { Cluster } from "./cluster_type_pb";
import { file_osac_public_v1_cluster_type } from "./cluster_type_pb";
import type { ComputeInstanceTemplate } from "./compute_instance_template_type_pb";
import { file_osac_public_v1_compute_instance_template_type } from "./compute_instance_template_type_pb";
import type { ComputeInstance } from "./compute_instance_type_pb";
import { file_osac_public_v1_compute_instance_type } from "./compute_instance_type_pb";
import type { DiskImage } from "./disk_image_type_pb";
import { file_osac_public_v1_disk_image_type } from "./disk_image_type_pb";
import type { HostType } from "./host_type_type_pb";
import { file_osac_public_v1_host_type_type } from "./host_type_type_pb";
import type { InstanceType } from "./instance_type_type_pb";
import { file_osac_public_v1_instance_type_type } from "./instance_type_type_pb";
import type { Project } from "./project_type_pb";
import { file_osac_public_v1_project_type } from "./project_type_pb";
import type { Tenant } from "./tenant_type_pb";
import { file_osac_public_v1_tenant_type } from "./tenant_type_pb";
import type { RoleBinding } from "./role_binding_type_pb";
import { file_osac_public_v1_role_binding_type } from "./role_binding_type_pb";
import type { Role } from "./role_type_pb";
import { file_osac_public_v1_role_type } from "./role_type_pb";
import type { Secret } from "./secret_type_pb";
import { file_osac_public_v1_secret_type } from "./secret_type_pb";
import type { Message } from "@bufbuild/protobuf";

/**
 * Describes the file osac/public/v1/event_type.proto.
 */
export const file_osac_public_v1_event_type: GenFile = /*@__PURE__*/
  fileDesc("Ch9vc2FjL3B1YmxpYy92MS9ldmVudF90eXBlLnByb3RvEg5vc2FjLnB1YmxpYy52MSLZBgoFRXZlbnQSCgoCaWQYASABKAkSJwoEdHlwZRgCIAEoDjIZLm9zYWMucHVibGljLnYxLkV2ZW50VHlwZRItCgl0aW1lc3RhbXAYJCABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEkAKE2JhcmVfbWV0YWxfaW5zdGFuY2UYAyABKAsyIS5vc2FjLnB1YmxpYy52MS5CYXJlTWV0YWxJbnN0YW5jZUgAEioKB2NsdXN0ZXIYBCABKAsyFy5vc2FjLnB1YmxpYy52MS5DbHVzdGVySAASOwoQY2x1c3Rlcl90ZW1wbGF0ZRgFIAEoCzIfLm9zYWMucHVibGljLnYxLkNsdXN0ZXJUZW1wbGF0ZUgAEjkKD2NsdXN0ZXJfdmVyc2lvbhgGIAEoCzIeLm9zYWMucHVibGljLnYxLkNsdXN0ZXJWZXJzaW9uSAASOwoQY29tcHV0ZV9pbnN0YW5jZRgHIAEoCzIfLm9zYWMucHVibGljLnYxLkNvbXB1dGVJbnN0YW5jZUgAEkwKGWNvbXB1dGVfaW5zdGFuY2VfdGVtcGxhdGUYCCABKAsyJy5vc2FjLnB1YmxpYy52MS5Db21wdXRlSW5zdGFuY2VUZW1wbGF0ZUgAEi8KCmRpc2tfaW1hZ2UYCSABKAsyGS5vc2FjLnB1YmxpYy52MS5EaXNrSW1hZ2VIABItCglob3N0X3R5cGUYCiABKAsyGC5vc2FjLnB1YmxpYy52MS5Ib3N0VHlwZUgAEjUKDWluc3RhbmNlX3R5cGUYCyABKAsyHC5vc2FjLnB1YmxpYy52MS5JbnN0YW5jZVR5cGVIABIqCgdwcm9qZWN0GAwgASgLMhcub3NhYy5wdWJsaWMudjEuUHJvamVjdEgAEiQKBHJvbGUYDSABKAsyFC5vc2FjLnB1YmxpYy52MS5Sb2xlSAASMwoMcm9sZV9iaW5kaW5nGA4gASgLMhsub3NhYy5wdWJsaWMudjEuUm9sZUJpbmRpbmdIABIoCgZzZWNyZXQYDyABKAsyFi5vc2FjLnB1YmxpYy52MS5TZWNyZXRIABIoCgZ0ZW5hbnQYECABKAsyFi5vc2FjLnB1YmxpYy52MS5UZW5hbnRIAEIJCgdwYXlsb2FkKoQBCglFdmVudFR5cGUSGgoWRVZFTlRfVFlQRV9VTlNQRUNJRklFRBAAEh0KGUVWRU5UX1RZUEVfT0JKRUNUX0NSRUFURUQQARIdChlFVkVOVF9UWVBFX09CSkVDVF9VUERBVEVEEAISHQoZRVZFTlRfVFlQRV9PQkpFQ1RfREVMRVRFRBADYgZwcm90bzM", [file_google_protobuf_timestamp, file_osac_public_v1_baremetal_instance_type, file_osac_public_v1_cluster_template_type, file_osac_public_v1_cluster_version_type, file_osac_public_v1_cluster_type, file_osac_public_v1_compute_instance_template_type, file_osac_public_v1_compute_instance_type, file_osac_public_v1_disk_image_type, file_osac_public_v1_host_type_type, file_osac_public_v1_instance_type_type, file_osac_public_v1_project_type, file_osac_public_v1_tenant_type, file_osac_public_v1_role_binding_type, file_osac_public_v1_role_type, file_osac_public_v1_secret_type]);

/**
 * Represents events delivered by the server.
 *
 * @generated from message osac.public.v1.Event
 */
export type Event = Message<"osac.public.v1.Event"> & {
  /**
   * Unique identifier of the event.
   *
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * Type of event.
   *
   * @generated from field: osac.public.v1.EventType type = 2;
   */
  type: EventType;

  /**
   * Time at which the event was generated.
   *
   * For EVENT_TYPE_OBJECT_DELETED, this is the authoritative deletion boundary: the time at which the object had no
   * remaining finalizers and the deletion event was generated. It is distinct from Metadata.deletion_timestamp, which
   * records when deletion was requested.
   *
   * @generated from field: google.protobuf.Timestamp timestamp = 36;
   */
  timestamp?: Timestamp | undefined;

  /**
   * Payload of the event.
   *
   * @generated from oneof osac.public.v1.Event.payload
   */
  payload: {
    /**
     * @generated from field: osac.public.v1.BareMetalInstance bare_metal_instance = 3;
     */
    value: BareMetalInstance;
    case: "bareMetalInstance";
  } | {
    /**
     * @generated from field: osac.public.v1.Cluster cluster = 4;
     */
    value: Cluster;
    case: "cluster";
  } | {
    /**
     * @generated from field: osac.public.v1.ClusterTemplate cluster_template = 5;
     */
    value: ClusterTemplate;
    case: "clusterTemplate";
  } | {
    /**
     * @generated from field: osac.public.v1.ClusterVersion cluster_version = 6;
     */
    value: ClusterVersion;
    case: "clusterVersion";
  } | {
    /**
     * @generated from field: osac.public.v1.ComputeInstance compute_instance = 7;
     */
    value: ComputeInstance;
    case: "computeInstance";
  } | {
    /**
     * @generated from field: osac.public.v1.ComputeInstanceTemplate compute_instance_template = 8;
     */
    value: ComputeInstanceTemplate;
    case: "computeInstanceTemplate";
  } | {
    /**
     * @generated from field: osac.public.v1.DiskImage disk_image = 9;
     */
    value: DiskImage;
    case: "diskImage";
  } | {
    /**
     * @generated from field: osac.public.v1.HostType host_type = 10;
     */
    value: HostType;
    case: "hostType";
  } | {
    /**
     * @generated from field: osac.public.v1.InstanceType instance_type = 11;
     */
    value: InstanceType;
    case: "instanceType";
  } | {
    /**
     * @generated from field: osac.public.v1.Project project = 12;
     */
    value: Project;
    case: "project";
  } | {
    /**
     * @generated from field: osac.public.v1.Role role = 13;
     */
    value: Role;
    case: "role";
  } | {
    /**
     * @generated from field: osac.public.v1.RoleBinding role_binding = 14;
     */
    value: RoleBinding;
    case: "roleBinding";
  } | {
    /**
     * @generated from field: osac.public.v1.Secret secret = 15;
     */
    value: Secret;
    case: "secret";
  } | {
    /**
     * @generated from field: osac.public.v1.Tenant tenant = 16;
     */
    value: Tenant;
    case: "tenant";
  } | { case: undefined; value?: undefined };
};

/**
 * Describes the message osac.public.v1.Event.
 * Use `create(EventSchema)` to create a new message.
 */
export const EventSchema: GenMessage<Event> = /*@__PURE__*/
  messageDesc(file_osac_public_v1_event_type, 0);

/**
 * @generated from enum osac.public.v1.EventType
 */
export enum EventType {
  /**
   * Unspecified means that the even type is unknown.
   *
   * @generated from enum value: EVENT_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * Means that a new object has been created.
   *
   * The payload will contain the representation of the object.
   *
   * @generated from enum value: EVENT_TYPE_OBJECT_CREATED = 1;
   */
  OBJECT_CREATED = 1,

  /**
   * Means that an existing object has been modified.
   *
   * The payload will contain the updated representation of the object.
   *
   * @generated from enum value: EVENT_TYPE_OBJECT_UPDATED = 2;
   */
  OBJECT_UPDATED = 2,

  /**
   * Means that an object has been deleted.
   *
   * The payload will contain the representation of the object right before it was deleted.
   *
   * @generated from enum value: EVENT_TYPE_OBJECT_DELETED = 3;
   */
  OBJECT_DELETED = 3,
}

/**
 * Describes the enum osac.public.v1.EventType.
 */
export const EventTypeSchema: GenEnum<EventType> = /*@__PURE__*/
  enumDesc(file_osac_public_v1_event_type, 0);

